apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: grafana
  ports:
    - protocol: TCP
      port: 3000       # porta interna do Grafana
      targetPort: 3000
      nodePort: 32000  # porta externa no Node
      name: http
