apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-nginx-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: app-nginx
  namespaceSelector:
    any: true
  endpoints:
    - port: metrics
      interval: 30s
