apiVersion: v1
kind: Service
metadata:
  name: app-java-service
spec:
  selector:
    app: app-java
  ports:
    - port: 80       # porta do serviço
      targetPort: 8080  # porta do container
  type: NodePort     # para aceder via browser no cluster local
