# apiVersion: v1
# kind: Service
# metadata:
#   name: app-java-service
# spec:
#   selector:
#     app: app-java
#   ports:
#     - port: 80
#       targetPort: 8080
#       nodePort: 30080
#   type: NodePort


apiVersion: v1
kind: Service
metadata:
  name: app-java-service
spec:
  type: NodePort
  selector:
    app: app-java
  ports:
    - protocol: TCP
      port: 8080          # porta interna do cluster
      targetPort: 8080    # porta do container
      nodePort: 30081     # porta exposta no host para aceder via browser

