apiVersion: v1
kind: Service
metadata:
  name: app-nginx-service
spec:
  type: NodePort
  selector:
    app: app-nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
    - name: metrics
      protocol: TCP
      port: 9113
      targetPort: 9113
      nodePort: 32168






