apiVersion: v1
kind: Service
metadata:
  name: app-nginx-service
spec:
  type: NodePort
  selector:
    app: app-nginx
  ports:
    - protocol: TCP
      port: 80          # porta interna do pod
      targetPort: 80    # porta no container
      nodePort: 30081   # porta exposta no host



