name: CI/CD Java Maven + Docker + Kubernetes

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Checkout do código
      - name: Checkout código
        uses: actions/checkout@v3

      # Compilar e testar
      - name: Compilar e testar Maven
        run: mvn clean verify

      # Login no Docker Hub
      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build da imagem Docker
      - name: Build Docker image
        run: docker build -t tomasreigota/app-java:latest .

      # Push da imagem Docker
      - name: Push Docker image
        run: docker push tomasreigota/app-java:latest

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      # Checkout do código
      - name: Checkout código
        uses: actions/checkout@v3

      # Configurar kubeconfig para o cluster k3d
      - name: Configurar kubeconfig
        shell: pwsh
        run: |
          $kubeDir = "$HOME\.kube"
          if (-Not (Test-Path $kubeDir)) {
            New-Item -ItemType Directory -Path $kubeDir
          }
          "${{ secrets.KUBECONFIG }}" | Out-File -Encoding ascii "$kubeDir\config"

      # Aplicar manifests Kubernetes
      - name: Deploy no Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      # Verificar pods e serviços
      - name: Verificar estado no cluster
        run: |
          kubectl get pods
          kubectl get svc
