name: CI/CD Nginx + Docker + Kubernetes

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t tomasreigota/app-nginx:latest .

      - name: Push Docker image
        run: docker push tomasreigota/app-nginx:latest

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar kubeconfig
        run: |
          if not exist "%USERPROFILE%\.kube" mkdir "%USERPROFILE%\.kube"
          echo %KUBECONFIG% > "%USERPROFILE%\.kube\config"
        shell: cmd
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}

      - name: Deploy no Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/monitor.yaml -n monitoring

      - name: Verificar estado no cluster
        run: |
          kubectl get pods
          kubectl get svc
          kubectl get servicemonitors -n monitoring

          