name: CI Java Maven - Teste

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted   # usa o runner local

    steps:
      # 1. Fazer checkout do código
      - name: Checkout código
        uses: actions/checkout@v3

      # 2. Compilar e testar com Maven
      - name: Compilar e testar
        run: mvn clean verify
